### ISSUE TITLE
Encrypting Credential Format

### ISSUE THREAD

**Issue by RoARene317** [ayangd/BimayInstantVicon#2]
It's gonna be very helpful if output text is encrypted since I am from Cyber Security students (1st semester btw) and it's gonna be good if you encrypt the credential file.

**Comment by ayangd** [comment]
Saving credential files are always unsafe because the hacker could just reverse-engineer the encryption of the program. But it's probably OK if the credential is not directly visible.

I'll put a reference of how not to store password [here](https://www.youtube.com/watch?v=8ZtInClXe1Q).

Thanks for the input though 😃
